/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package slidervolversion2;

/**
 *
 * @author andres
 */
public class SliderVolPanel extends javax.swing.JPanel {

    /**
     * Creates new form NotaPanel
     */
    public SliderVolPanel() {
        initComponents();
    }

    public RangosVolumen getSelectedValue() {
        return new RangosVolumen(jSliderRango1.getValue(), jSliderRango2.getValue(), jSliderRango3.getValue());
    }

    public void mostrarValores() {
        this.jLabelRango1.setText(this.jSliderRango1.getValue() + "%");
        this.jLabelRango2.setText(this.jSliderRango2.getValue() + "%");
        this.jLabelRango3.setText(this.jSliderRango3.getValue() + "%");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSliderRango1 = new javax.swing.JSlider();
        jSliderRango2 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelRango2 = new javax.swing.JLabel();
        jLabelRango1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSliderRango3 = new javax.swing.JSlider();
        jLabelRango3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jSliderRango1.setValue(25);
        jSliderRango1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderRango1StateChanged(evt);
            }
        });

        jSliderRango2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderRango2StateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Rango 2:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Rango 1:");

        jLabelRango2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelRango2.setText("50%");

        jLabelRango1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelRango1.setText("25%");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Rango 3:");

        jSliderRango3.setValue(75);
        jSliderRango3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderRango3StateChanged(evt);
            }
        });

        jLabelRango3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelRango3.setText("75%");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("RANGOS DE LA NOTA MUSICAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSliderRango1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelRango1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSliderRango2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelRango2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSliderRango3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelRango3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel4)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jSliderRango1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRango1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jSliderRango2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRango2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jSliderRango3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRango3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderRango1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderRango1StateChanged
        if (this.jSliderRango1.getValue() >= this.jSliderRango2.getValue()) {
            this.jSliderRango2.setValue(this.jSliderRango1.getValue());
        }
        this.mostrarValores();
    }//GEN-LAST:event_jSliderRango1StateChanged

    private void jSliderRango2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderRango2StateChanged
        if (this.jSliderRango2.getValue() >= this.jSliderRango3.getValue()) {
            this.jSliderRango3.setValue(this.jSliderRango2.getValue());
        }
        this.mostrarValores();
    }//GEN-LAST:event_jSliderRango2StateChanged

    private void jSliderRango3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderRango3StateChanged
        this.jSliderRango3.setValue(this.jSliderRango3.getValue());
        this.mostrarValores();
    }//GEN-LAST:event_jSliderRango3StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelRango1;
    private javax.swing.JLabel jLabelRango2;
    private javax.swing.JLabel jLabelRango3;
    private javax.swing.JSlider jSliderRango1;
    private javax.swing.JSlider jSliderRango2;
    private javax.swing.JSlider jSliderRango3;
    // End of variables declaration//GEN-END:variables
}
