/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebaslidervolapg;

import javax.swing.JOptionPane;

/**
 *
 * @author andres
 */
public class PruebaSliderVol extends javax.swing.JFrame {

    /**
     * Creates new form PruebaSliderVol
     */
    public PruebaSliderVol() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSliderVolumenNota = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabelValorNota = new javax.swing.JLabel();
        sliderVolComponente2 = new slidervolapg.SliderVolComponente();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSliderVolumenNota.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jSliderVolumenNota.setMajorTickSpacing(5);
        jSliderVolumenNota.setMinorTickSpacing(1);
        jSliderVolumenNota.setPaintLabels(true);
        jSliderVolumenNota.setPaintTicks(true);
        jSliderVolumenNota.setSnapToTicks(true);
        jSliderVolumenNota.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSliderVolumenNota.setPreferredSize(new java.awt.Dimension(300, 50));
        jSliderVolumenNota.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderVolumenNotaStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Volumen de nota:");

        jLabelValorNota.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelValorNota.setText("50 %");

        sliderVolComponente2.setColor1(java.awt.Color.blue);
        sliderVolComponente2.setColor2(java.awt.Color.green);
        sliderVolComponente2.setColor3(java.awt.Color.yellow);
        sliderVolComponente2.setColor4(java.awt.Color.red);
        sliderVolComponente2.setStringPainted(true);
        sliderVolComponente2.setValue(50);
        sliderVolComponente2.addRangoAlcanzadoListener(new slidervolapg.SliderVolComponente.RangoAlcanzadoListener() {
            public void zonaVolumenAltoAlcanzada(slidervolapg.SliderVolComponente.RangoAlcanzado evt) {
                sliderVolComponente2ZonaVolumenAltoAlcanzada(evt);
            }
            public void zonaVolumenBajoAlcanzada(slidervolapg.SliderVolComponente.RangoAlcanzado evt) {
                sliderVolComponente2ZonaVolumenBajoAlcanzada(evt);
            }
            public void zonaVolumenMedioAlcanzada(slidervolapg.SliderVolComponente.RangoAlcanzado evt) {
                sliderVolComponente2ZonaVolumenMedioAlcanzada(evt);
            }
            public void zonaVolumenMuyBajoAlcanzada(slidervolapg.SliderVolComponente.RangoAlcanzado evt) {
                sliderVolComponente2ZonaVolumenMuyBajoAlcanzada(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabelValorNota)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sliderVolComponente2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSliderVolumenNota, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelValorNota))
                .addGap(32, 32, 32)
                .addComponent(jSliderVolumenNota, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(sliderVolComponente2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderVolumenNotaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderVolumenNotaStateChanged
        this.establecerValor();
    }//GEN-LAST:event_jSliderVolumenNotaStateChanged

    private void sliderVolComponente2ZonaVolumenAltoAlcanzada(slidervolapg.SliderVolComponente.RangoAlcanzado evt) {//GEN-FIRST:event_sliderVolComponente2ZonaVolumenAltoAlcanzada
       // Define el mensaje y el título
        String mensaje = "El volumen está alto";
        String titulo = "VOLUMEN ALTO";

        // Muestra el JOptionPane con el título y mensaje especificados
        JOptionPane.showMessageDialog(null, mensaje, titulo, JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_sliderVolComponente2ZonaVolumenAltoAlcanzada

    private void sliderVolComponente2ZonaVolumenBajoAlcanzada(slidervolapg.SliderVolComponente.RangoAlcanzado evt) {//GEN-FIRST:event_sliderVolComponente2ZonaVolumenBajoAlcanzada
        // Define el mensaje y el título
        String mensaje = "El volumen está bajo";
        String titulo = "VOLUMEN BAJO";

        // Muestra el JOptionPane con el título y mensaje especificados
        JOptionPane.showMessageDialog(null, mensaje, titulo, JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_sliderVolComponente2ZonaVolumenBajoAlcanzada

    private void sliderVolComponente2ZonaVolumenMedioAlcanzada(slidervolapg.SliderVolComponente.RangoAlcanzado evt) {//GEN-FIRST:event_sliderVolComponente2ZonaVolumenMedioAlcanzada
        // Define el mensaje y el título
        String mensaje = "El volumen está en nivel medio";
        String titulo = "VOLUMEN MEDIO";

        // Muestra el JOptionPane con el título y mensaje especificados
        JOptionPane.showMessageDialog(null, mensaje, titulo, JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_sliderVolComponente2ZonaVolumenMedioAlcanzada

    private void sliderVolComponente2ZonaVolumenMuyBajoAlcanzada(slidervolapg.SliderVolComponente.RangoAlcanzado evt) {//GEN-FIRST:event_sliderVolComponente2ZonaVolumenMuyBajoAlcanzada
        // Define el mensaje y el título
        String mensaje = "El volumen está muy bajo";
        String titulo = "VOLUMEN MUY BAJO";

        // Muestra el JOptionPane con el título y mensaje especificados
        JOptionPane.showMessageDialog(null, mensaje, titulo, JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_sliderVolComponente2ZonaVolumenMuyBajoAlcanzada

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaSliderVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaSliderVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaSliderVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaSliderVol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaSliderVol().setVisible(true);
            }
        });
    }

    public void establecerValor() {
        this.jLabelValorNota.setText(this.jSliderVolumenNota.getValue()+" %");
        //this.sliderVolComponente1.setValue(this.jSliderVolumenNota.getValue());
        this.sliderVolComponente2.setValue(this.jSliderVolumenNota.getValue());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelValorNota;
    private javax.swing.JSlider jSliderVolumenNota;
    private slidervolapg.SliderVolComponente sliderVolComponente2;
    // End of variables declaration//GEN-END:variables
}
