/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package actividad3;

import javax.swing.JOptionPane;

/**
 *
 * @author elite
 */
public class FORMULARIO_PRINCIPAL_JFRAME extends javax.swing.JFrame {

    /**
     * Creates new form FORMULARIO_PRINCIPAL_JFRAME
     */
    public FORMULARIO_PRINCIPAL_JFRAME() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1Datos = new javax.swing.JMenu();
        jMenu2Salir = new javax.swing.JMenu();
        jMenu3Ayuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\elite\\Downloads\\images.jpeg")); // NOI18N

        jMenu1Datos.setText("Datos");
        jMenu1Datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1DatosMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1Datos);

        jMenu2Salir.setText("Salir");
        jMenu2Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2SalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2Salir);

        jMenu3Ayuda.setText("Ayuda");
        jMenu3Ayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3AyudaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3Ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel1)
                .addContainerGap(397, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1DatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1DatosMouseClicked
        // TODO add your handling code here:
        DATOS_JDIALOG formularioDatos = new DATOS_JDIALOG(this, true);//lanzamiento de ventana modal desde el padre JFRAME PRINCIPAL con dos parámetros uno de la ventana padre y otro que indica si es modal o no modal (en este caso indicamos con true como )
        formularioDatos.setVisible(true);//añadimos visibilidad a la ventana.
    }//GEN-LAST:event_jMenu1DatosMouseClicked

    private void jMenu2SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2SalirMouseClicked
        // TODO add your handling code here:
        // BOTON SALIR
        // Pregunta al usuario si desea salir
        int opcion = JOptionPane.showConfirmDialog(null, "¿Desea salir de la aplicación?", "Salir", JOptionPane.YES_NO_OPTION);

        // Verifica la respuesta del usuario
        if (opcion == JOptionPane.YES_OPTION) {
            // Si la respuesta es Sí, finaliza la aplicación
            System.exit(0);
        }


    }//GEN-LAST:event_jMenu2SalirMouseClicked

    private void jMenu3AyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3AyudaMouseClicked
        // TODO add your handling code here:
        // CLICK EN AYUDA
        // Obtén el correo electrónico y el número de teléfono (puedes cambiar estos valores según tus necesidades)
        String email = "MiguelRepasoDI@example.com";
        String telefono = "+123456789";

        // Construye el mensaje
        String mensaje = "Para contacto:\nEmail: " + email + "\nTeléfono: " + telefono;

        // Muestra el mensaje en un cuadro de diálogo
        JOptionPane.showMessageDialog(null, mensaje, "Información de contacto", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenu3AyudaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORMULARIO_PRINCIPAL_JFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORMULARIO_PRINCIPAL_JFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORMULARIO_PRINCIPAL_JFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORMULARIO_PRINCIPAL_JFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORMULARIO_PRINCIPAL_JFRAME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1Datos;
    private javax.swing.JMenu jMenu2Salir;
    private javax.swing.JMenu jMenu3Ayuda;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
