/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio01;

/**
 *
 * @author Alumno
 */
public class Articulos extends java.awt.Dialog {

    /**
     * Creates new form Articulos
     */
    public Articulos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_gama = new javax.swing.ButtonGroup();
        jLabel_codigo = new javax.swing.JLabel();
        jLabel_nombre = new javax.swing.JLabel();
        jPanel_gama = new javax.swing.JPanel();
        jRadioButton_blanca = new javax.swing.JRadioButton();
        jRadioButton_marron = new javax.swing.JRadioButton();
        jRadioButton_PAE = new javax.swing.JRadioButton();
        jLabel_Fecha = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jSpinner_fechaAlta = new javax.swing.JSpinner();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel_codigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_codigo.setText("Cód.:");
        jLabel_codigo.setToolTipText("Máximo 5 caracteres Numéricos (0-9)");

        jLabel_nombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_nombre.setText("Nombre");
        jLabel_nombre.setToolTipText("Máximo 10 caracteres alfanuméricos");

        jPanel_gama.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gama", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel_gama.setToolTipText("Las gamas sólo pueden ser Blanca, Marrón y PAE");

        buttonGroup_gama.add(jRadioButton_blanca);
        jRadioButton_blanca.setText("Blanca");
        jPanel_gama.add(jRadioButton_blanca);

        buttonGroup_gama.add(jRadioButton_marron);
        jRadioButton_marron.setText("Marrón");
        jPanel_gama.add(jRadioButton_marron);

        buttonGroup_gama.add(jRadioButton_PAE);
        jRadioButton_PAE.setText("PAE");
        jPanel_gama.add(jRadioButton_PAE);

        jLabel_Fecha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_Fecha.setText("Fecha de Alta");
        jLabel_Fecha.setToolTipText("Formato fecha:  dd/mm/aa");

        txtCodigo.setToolTipText("Máximo 5 caracteres Numéricos (0-9)");
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        txtNombre.setToolTipText("Máximo 10 caracteres alfanuméricos");
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        jSpinner_fechaAlta.setModel(new javax.swing.SpinnerDateModel());
        jSpinner_fechaAlta.setToolTipText("Formato fecha:  dd/mm/aa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel_gama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_codigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigo)
                            .addComponent(txtNombre)
                            .addComponent(jSpinner_fechaAlta))))
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Fecha)
                    .addComponent(jSpinner_fechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_gama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        //obtenemos la tecla pulsada por el usuario
        char TestChar = evt.getKeyChar();
        // si la tecla no es digito o bien la longitud del campo código ya supera los 5 digitos la ignoramos
        if (!(Character.isDigit(TestChar)) || txtCodigo.getText().length() >= 5) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
          //Validación campo Nombre que solo permite caracteres alfabéticos
        //es igual que el anterior solo que hacemos el if separado (no mezclamos las condiciones)
        //y ahora en lugar de controlar dígitos del 0 al 9, controlamos que la tecla introducida
        //sea alfanumérica
    
       char TestChar=evt.getKeyChar();                     
       if(txtNombre.getText().length()>=10){
            evt.consume();
        }
        if(!Character.isAlphabetic(TestChar)){
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Articulos dialog = new Articulos(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_gama;
    private javax.swing.JLabel jLabel_Fecha;
    private javax.swing.JLabel jLabel_codigo;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JPanel jPanel_gama;
    private javax.swing.JRadioButton jRadioButton_PAE;
    private javax.swing.JRadioButton jRadioButton_blanca;
    private javax.swing.JRadioButton jRadioButton_marron;
    private javax.swing.JSpinner jSpinner_fechaAlta;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
