package MisControles;

/**
 *
 * @author andres
 */
public class TextFieldPanel extends javax.swing.JPanel {

    private TextFieldExtended textField;

    /**
     * Creates new form TextFieldPanel
     */
    public TextFieldPanel() {
        initComponents();
    }

    public void setTextField(TextFieldExtended textField) {
        this.textField = textField;
        this.jSliderLongitud.setValue(textField.getLongitud()); // Sincroniza el slider con la longitud actual
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSliderLongitud = new javax.swing.JSlider();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelLongitud = new javax.swing.JLabel();

        jSliderLongitud.setMajorTickSpacing(1);
        jSliderLongitud.setMaximum(30);
        jSliderLongitud.setPaintLabels(true);
        jSliderLongitud.setPaintTicks(true);
        jSliderLongitud.setSnapToTicks(true);
        jSliderLongitud.setValue(7);
        jSliderLongitud.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderLongitudStateChanged(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTitulo.setText("La longitud del campo texto es:");

        jLabelLongitud.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelLongitud.setText("7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLongitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSliderLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderLongitudStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderLongitudStateChanged
        this.mostrarValorLongitud();
        if (this.textField != null) {
            int nuevaLongitud = this.jSliderLongitud.getValue();
            this.textField.setLongitud(nuevaLongitud);
            System.out.println("Nueva longitud: " + nuevaLongitud);
            System.out.println("Longitud actual en TextFieldExtended: " + this.textField.getLongitud());
        }
    }//GEN-LAST:event_jSliderLongitudStateChanged

    public int getSelectedValue() {
        return (int) this.jSliderLongitud.getValue();
    }

    public void mostrarValorLongitud() {
        this.jLabelLongitud.setText(String.valueOf(this.jSliderLongitud.getValue()));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLongitud;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JSlider jSliderLongitud;
    // End of variables declaration//GEN-END:variables
}
