/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tarea01llr_;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author lR
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    private void mostrarFormulario() {
        // Cuando se guarda correctamente, aqui se aprovechará para inicializar
        //Inicializamos todos los elementos por defecto
        this.textoAutorLibro.setText("");
        this.textoDNI.setText("");
        this.textoISBN.setText("");
        this.textoNombre.setText("");
        this.textoTelefono.setText("");
        this.textoTituloLibro.setText("");
        //Deselecciono los checks
        this.chkTopic1.setSelected(false);
        this.chkTopic2.setSelected(false);
        this.chkTopic3.setSelected(false);
        //Inicializo los combos
        this.comboEditorial.setSelectedIndex(0);
        this.comboEncuadernacion.setSelectedIndex(0);
        this.comboMaterias.setSelectedIndex(0);

        // Hacemos que la pantalla se vea
        //Ponemos los topics por defecto de la primera opcion del comboMaterias
        chkTopic1.setText("Análisis de alimentos");
        chkTopic2.setText("Industria alimentaria");
        chkTopic3.setText("Nutrición y dietética");
        //Inicializar fecha del spinner
        Date fechaInicial = Calendar.getInstance().getTime();
        SpinnerDateModel mode1 = new SpinnerDateModel(fechaInicial, null, null, Calendar.DAY_OF_MONTH);
        SpinnerDateModel mode2 = new SpinnerDateModel(fechaInicial, null, null, Calendar.DAY_OF_MONTH);
        spinnerEntrega.setModel(mode1);
        spinnerFechaPrestamo.setModel(mode2);
        //Damos formato a la fecha del spinner
        spinnerEntrega.setEditor(new JSpinner.DateEditor(spinnerEntrega, "dd/MM/yyyy"));
        spinnerFechaPrestamo.setEditor(new JSpinner.DateEditor(spinnerFechaPrestamo, "dd/MM/yyyy"));

        //Una vez formateado todo, hacemos visible el formulario
        // Obtener el tamaño de la pantalla
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Obtener el tamaño de la ventana emergente
        Dimension frameSize = DatosPrestamo.getSize();

        // Calcular las coordenadas X e Y para centrar el dialogo emergente
        int x = (screenSize.width - frameSize.width) / 2;
        int y = (screenSize.height - frameSize.height) / 2;

        // Establecer las coordenadas para centrar el dialogo emergente
        DatosPrestamo.setLocation(x, y);

        // Mostramos el dialogo emergente
        DatosPrestamo.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DatosPrestamo = new javax.swing.JDialog();
        panelFormularioPrestamo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textoDNI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textoTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textoISBN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textoTituloLibro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textoAutorLibro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboEditorial = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        comboEncuadernacion = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        comboMaterias = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        panelTopics = new javax.swing.JPanel();
        chkTopic1 = new javax.swing.JCheckBox();
        chkTopic2 = new javax.swing.JCheckBox();
        chkTopic3 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        spinnerFechaPrestamo = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        spinnerEntrega = new javax.swing.JSpinner();
        botonGuardar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        panelContenido = new javax.swing.JPanel();
        etiquetaLogo = new javax.swing.JLabel();
        botonNuevoPrestamo = new javax.swing.JButton();
        barraMenuPrestamos = new javax.swing.JMenuBar();
        menuPrestamo = new javax.swing.JMenu();
        menuItemNuevoPrestamo = new javax.swing.JMenuItem();
        menuItemSalir = new javax.swing.JMenuItem();

        DatosPrestamo.setTitle("Formulario Préstamo");
        DatosPrestamo.setBackground(new java.awt.Color(255, 204, 204));
        DatosPrestamo.setMinimumSize(new java.awt.Dimension(900, 500));
        DatosPrestamo.setModal(true);
        DatosPrestamo.setResizable(false);

        panelFormularioPrestamo.setBackground(new java.awt.Color(255, 255, 204));
        panelFormularioPrestamo.setToolTipText("");
        panelFormularioPrestamo.setMaximumSize(new java.awt.Dimension(400, 400));
        panelFormularioPrestamo.setPreferredSize(new java.awt.Dimension(400, 200));
        panelFormularioPrestamo.setLayout(new java.awt.GridLayout(12, 2));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Nombre/Apellidos:");
        panelFormularioPrestamo.add(jLabel1);

        textoNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoNombre.setToolTipText("Introduzca su nombre y apellidos");
        textoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoNombreKeyTyped(evt);
            }
        });
        panelFormularioPrestamo.add(textoNombre);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("DNI:");
        panelFormularioPrestamo.add(jLabel2);

        textoDNI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoDNI.setToolTipText("Introduzca su DNI");
        textoDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoDNIKeyTyped(evt);
            }
        });
        panelFormularioPrestamo.add(textoDNI);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Teléfono:");
        panelFormularioPrestamo.add(jLabel3);

        textoTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoTelefono.setToolTipText("Introduzca su teléfono");
        textoTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoTelefonoKeyTyped(evt);
            }
        });
        panelFormularioPrestamo.add(textoTelefono);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("ISBN:");
        panelFormularioPrestamo.add(jLabel4);

        textoISBN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoISBN.setToolTipText("Introduzca el ISBN");
        textoISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoISBNKeyTyped(evt);
            }
        });
        panelFormularioPrestamo.add(textoISBN);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Título del libro:");
        panelFormularioPrestamo.add(jLabel5);

        textoTituloLibro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoTituloLibro.setToolTipText("Introduzca el título del libro");
        textoTituloLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoTituloLibroKeyTyped(evt);
            }
        });
        panelFormularioPrestamo.add(textoTituloLibro);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Autor libro:");
        panelFormularioPrestamo.add(jLabel6);

        textoAutorLibro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoAutorLibro.setToolTipText("Introduzca el autor del libro");
        textoAutorLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoAutorLibroKeyTyped(evt);
            }
        });
        panelFormularioPrestamo.add(textoAutorLibro);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Editorial:");
        panelFormularioPrestamo.add(jLabel7);

        comboEditorial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urano Ediciones", "Círculo rojo", "Vicens Vives", "Altamar" }));
        comboEditorial.setToolTipText("Seleccione la editorial");
        comboEditorial.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboEditorialItemStateChanged(evt);
            }
        });
        panelFormularioPrestamo.add(comboEditorial);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Tipo de encuadernación:");
        panelFormularioPrestamo.add(jLabel8);

        comboEncuadernacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rústica", "Tapa Dura", "Piel" }));
        comboEncuadernacion.setToolTipText("Seleccione el tipo de encuadernación (Disponible para Circulo Rojo y Vincens Vives).");
        comboEncuadernacion.setEnabled(false);
        panelFormularioPrestamo.add(comboEncuadernacion);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Materias:");
        panelFormularioPrestamo.add(jLabel9);

        comboMaterias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentación-Nutrición", "Medicina", "Derecho", "Música" }));
        comboMaterias.setToolTipText("Seleccione la materia del libro");
        comboMaterias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboMateriasItemStateChanged(evt);
            }
        });
        panelFormularioPrestamo.add(comboMaterias);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Topics:");
        panelFormularioPrestamo.add(jLabel12);

        panelTopics.setBackground(new java.awt.Color(255, 255, 204));
        panelTopics.setToolTipText("Seleccione la temática de la materia");
        panelTopics.setLayout(new javax.swing.BoxLayout(panelTopics, javax.swing.BoxLayout.LINE_AXIS));
        panelTopics.add(chkTopic1);
        panelTopics.add(chkTopic2);
        panelTopics.add(chkTopic3);

        panelFormularioPrestamo.add(panelTopics);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Fecha préstamo libro:");
        panelFormularioPrestamo.add(jLabel10);

        spinnerFechaPrestamo.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_YEAR));
        spinnerFechaPrestamo.setToolTipText("Fecha del préstamo del libro");
        panelFormularioPrestamo.add(spinnerFechaPrestamo);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Fecha entrega libro:");
        panelFormularioPrestamo.add(jLabel11);

        spinnerEntrega.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_YEAR));
        spinnerEntrega.setToolTipText("Fecha de entrega del libro");
        panelFormularioPrestamo.add(spinnerEntrega);

        botonGuardar.setBackground(new java.awt.Color(204, 255, 204));
        botonGuardar.setText("Guardar registro");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(255, 153, 153));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DatosPrestamoLayout = new javax.swing.GroupLayout(DatosPrestamo.getContentPane());
        DatosPrestamo.getContentPane().setLayout(DatosPrestamoLayout);
        DatosPrestamoLayout.setHorizontalGroup(
            DatosPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosPrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFormularioPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(DatosPrestamoLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(botonGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DatosPrestamoLayout.setVerticalGroup(
            DatosPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosPrestamoLayout.createSequentialGroup()
                .addComponent(panelFormularioPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatosPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar)
                    .addComponent(botonSalir))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido a su Software de Préstamos");
        setBackground(new java.awt.Color(204, 255, 204));
        setResizable(false);

        panelContenido.setBackground(new java.awt.Color(255, 255, 204));

        etiquetaLogo.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaLogo.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        etiquetaLogo.setForeground(new java.awt.Color(204, 153, 0));
        etiquetaLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen.png"))); // NOI18N
        etiquetaLogo.setText("BookTo");
        etiquetaLogo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));

        botonNuevoPrestamo.setBackground(new java.awt.Color(255, 204, 204));
        botonNuevoPrestamo.setText("Nuevo Préstamo");
        botonNuevoPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoPrestamoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiquetaLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(botonNuevoPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(etiquetaLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonNuevoPrestamo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        barraMenuPrestamos.setBackground(new java.awt.Color(255, 255, 204));

        menuPrestamo.setText("Préstamos");

        menuItemNuevoPrestamo.setText("Nuevo Préstamo");
        menuItemNuevoPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNuevoPrestamoActionPerformed(evt);
            }
        });
        menuPrestamo.add(menuItemNuevoPrestamo);

        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menuPrestamo.add(menuItemSalir);

        barraMenuPrestamos.add(menuPrestamo);

        setJMenuBar(barraMenuPrestamos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        String campoVacio = "";
        if (this.textoAutorLibro.getText().isEmpty()) {
            campoVacio += "Autor del libro\n";
            this.textoAutorLibro.setBackground(Color.RED);
        }
        if (this.textoDNI.getText().isEmpty()) {
            campoVacio += "Número de identificación fiscal\n";
            this.textoDNI.setBackground(Color.RED);
        }
        if (this.textoISBN.getText().isEmpty()) {
            campoVacio += "ISBN\n";
            this.textoISBN.setBackground(Color.RED);
        }
        if (this.textoNombre.getText().isEmpty()) {
            campoVacio += "Nombre y Apellidos\n";
            this.textoNombre.setBackground(Color.RED);
        }
        if (this.textoTelefono.getText().isEmpty()) {
            campoVacio += "Teléfono\n";
            this.textoTelefono.setBackground(Color.RED);
        }
        if (this.textoTituloLibro.getText().isEmpty()) {
            campoVacio += "Título\n";
            this.textoTituloLibro.setBackground(Color.RED);
        }
        JFrame frame = new JFrame("Aviso");
        if (campoVacio.isEmpty()) {
            JOptionPane.showMessageDialog(frame, "Registro guardado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            mostrarFormulario();
        } else {
            // Mostrar un cuadro de diálogo de aviso

            JOptionPane.showMessageDialog(frame, "Por favor, cumplimente los campos:\n" + campoVacio, "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void comboEditorialItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboEditorialItemStateChanged

        // Nos quedamos con el indice actual del combo
        int indiceActual = comboEditorial.getSelectedIndex();
        // Selecionamos el combo de encuadernacion como habilitado si el indice que cogemos
        // es 1 Circulo Rojo o 2 Vincens Vices. En caso contrario estara deshabilitado
        comboEncuadernacion.setEnabled(indiceActual == 1 || indiceActual == 2);
    }//GEN-LAST:event_comboEditorialItemStateChanged

    private void botonNuevoPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoPrestamoActionPerformed
        mostrarFormulario();
    }//GEN-LAST:event_botonNuevoPrestamoActionPerformed

    private void menuItemNuevoPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNuevoPrestamoActionPerformed

        mostrarFormulario();
    }//GEN-LAST:event_menuItemNuevoPrestamoActionPerformed

    private void comboMateriasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboMateriasItemStateChanged
        // TODO add your handling code here:
        int indiceSeleccionado = comboMaterias.getSelectedIndex();
        // En función del indice de combo materias mostramos los topics necesarios(checks)    
        switch (indiceSeleccionado) {
            case 0:
                chkTopic1.setText("Análisis de alimentos");
                chkTopic2.setText("Industria alimentaria");
                chkTopic3.setText("Nutrición y dietética");
                break;
            case 1:
                chkTopic1.setText("Neurología");
                chkTopic2.setText("Patología");
                chkTopic3.setText("Medicina General");
                break;
            case 2:
                chkTopic1.setText("Derecho Privado");
                chkTopic2.setText("Derecho Público");
                chkTopic3.setText("Derecho militar");
                break;
            case 3:
                chkTopic1.setText("Flamenco");
                chkTopic2.setText("Música clásica");
                chkTopic3.setText("Teoría e historia de la música");
                break;
        }
    }//GEN-LAST:event_comboMateriasItemStateChanged

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        Boolean hayDatos = false;
        if (!this.textoAutorLibro.getText().isEmpty()) {
            hayDatos = true;
        }
        if (!this.textoDNI.getText().isEmpty()) {
            hayDatos = true;
        }
        if (!this.textoISBN.getText().isEmpty()) {
            hayDatos = true;
        }
        if (!this.textoNombre.getText().isEmpty()) {
            hayDatos = true;
        }
        if (!this.textoTelefono.getText().isEmpty()) {
            hayDatos = true;
        }
        if (!this.textoTituloLibro.getText().isEmpty()) {
            hayDatos = true;
        }
        
        if (hayDatos) {
            JFrame frame = new JFrame("Ey, no tan rápido");
            String mensaje = "¿Realmente quiere salir?";
            String titulo = "Confirmar Salida";
            int opcion = JOptionPane.showConfirmDialog(frame, mensaje, titulo, JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                DatosPrestamo.dispose();
            } else {
                frame.dispose();
            }
        } else {
            // Cerramos solo el Formulario
            DatosPrestamo.dispose();
        }
    }//GEN-LAST:event_botonSalirActionPerformed

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
       
        System.exit(0);
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void textoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoNombreKeyTyped
         // Como el máximo es 30 carácteres, no dejamos que el texto supere esa longitud
        // acotandolo a 30 caracteres de manera dinámica.
        textoNombre.setBackground(Color.WHITE);
        if (textoNombre.getText().length() > 30) {
            // evitamos escribir mas de 30 caracteres
            evt.consume();
        }
    }//GEN-LAST:event_textoNombreKeyTyped

    private void textoDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoDNIKeyTyped
        
        textoDNI.setBackground(Color.WHITE);
        if (textoDNI.getText().length() > 10) {
            evt.consume();
        }
    }//GEN-LAST:event_textoDNIKeyTyped

    private void textoTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoTelefonoKeyTyped
        //Si metemos un valor que no sea numerico, no se escribira
        textoTelefono.setBackground(Color.WHITE);
        try {
            int numero = Integer.parseInt(String.valueOf(evt.getKeyChar()));
        } catch (NumberFormatException e) {
            evt.consume();
        }
        if (textoTelefono.getText().length() > 9) {
            //evitamos que se escriba el caracter > 9
            evt.consume();
        }
    }//GEN-LAST:event_textoTelefonoKeyTyped

    private void textoISBNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoISBNKeyTyped
        
        textoISBN.setBackground(Color.WHITE);
        try {
            int numero = Integer.parseInt(String.valueOf(evt.getKeyChar()));
        } catch (NumberFormatException e) {
            evt.consume();
        }
        if (textoISBN.getText().length() > 13) {
            //otra forma de evitar que se escriba el ultimo caracter
            evt.consume();
        }
    }//GEN-LAST:event_textoISBNKeyTyped

    private void textoTituloLibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoTituloLibroKeyTyped
        textoTituloLibro.setBackground(Color.WHITE);
        if (textoTituloLibro.getText().length() > 30) {
            evt.consume();
        }
    }//GEN-LAST:event_textoTituloLibroKeyTyped

    private void textoAutorLibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoAutorLibroKeyTyped
       textoAutorLibro.setBackground(Color.WHITE);
        if (textoAutorLibro.getText().length() > 20) {
            evt.consume();
        }
    }//GEN-LAST:event_textoAutorLibroKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame ventana = new Principal();
                // Obtener el tamaño de la pantalla
                Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

                // Obtener el tamaño del JFrame
                Dimension frameSize = ventana.getSize();

                // Calcular las coordenadas X e Y para centrar el JFrame
                int x = (screenSize.width - frameSize.width) / 2;
                int y = (screenSize.height - frameSize.height) / 2;

                // Establecer las coordenadas para centrar el JFrame
                ventana.setLocation(x, y);

                // Mostramos ventana
                ventana.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DatosPrestamo;
    private javax.swing.JMenuBar barraMenuPrestamos;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonNuevoPrestamo;
    private javax.swing.JButton botonSalir;
    private javax.swing.JCheckBox chkTopic1;
    private javax.swing.JCheckBox chkTopic2;
    private javax.swing.JCheckBox chkTopic3;
    private javax.swing.JComboBox<String> comboEditorial;
    private javax.swing.JComboBox<String> comboEncuadernacion;
    private javax.swing.JComboBox<String> comboMaterias;
    private javax.swing.JLabel etiquetaLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem menuItemNuevoPrestamo;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenu menuPrestamo;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelFormularioPrestamo;
    private javax.swing.JPanel panelTopics;
    private javax.swing.JSpinner spinnerEntrega;
    private javax.swing.JSpinner spinnerFechaPrestamo;
    private javax.swing.JTextField textoAutorLibro;
    private javax.swing.JTextField textoDNI;
    private javax.swing.JTextField textoISBN;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoTelefono;
    private javax.swing.JTextField textoTituloLibro;
    // End of variables declaration//GEN-END:variables
}
