/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebastarea03;

import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import planificador.Alarma;

/**
 *
 * @author Alejandro
 */
public class PruebaPlanificador extends javax.swing.JFrame {

    /**
     * Creates new form PruebaPlanificador
     */
    public PruebaPlanificador() {
        initComponents();
        
        planificador.addActivarAlarma(new planificador.Planificador.ActivarAlarma() {
            @Override
            public void capturarActivarAlarma(planificador.Planificador.AlarmaEvent evt){
                JOptionPane.showMessageDialog(null, planificador.getAlarma().getTarea(), "Alarma planificador", JOptionPane.WARNING_MESSAGE);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupFormatoFecha = new javax.swing.ButtonGroup();
        buttonGroupFormatoHora = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSpinnerFechaHora = new javax.swing.JSpinner();
        jLabelFechaHora = new javax.swing.JLabel();
        jLabelTarea = new javax.swing.JLabel();
        jTextFieldTarea = new javax.swing.JTextField();
        jPanelFormatoFecha = new javax.swing.JPanel();
        jRadioButtonFechaLarga = new javax.swing.JRadioButton();
        jRadioButtonFechaCorta = new javax.swing.JRadioButton();
        jPanelFormatoHora = new javax.swing.JPanel();
        jRadioButtonHoras24 = new javax.swing.JRadioButton();
        jRadioButtonHoras12 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        planificador = new planificador.Planificador();
        jButtonProgAlarma = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Planificador - Tarea03");
        setBounds(new java.awt.Rectangle(100, 100, 0, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Programar alarma"));

        jSpinnerFechaHora.setModel(new javax.swing.SpinnerDateModel());

        jLabelFechaHora.setText("Fecha y hora:");

        jLabelTarea.setText("Tarea:");

        jTextFieldTarea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTareaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelFechaHora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinnerFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelTarea)
                    .addComponent(jTextFieldTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaHora))
                .addGap(18, 18, 18)
                .addComponent(jLabelTarea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanelFormatoFecha.setBorder(javax.swing.BorderFactory.createTitledBorder("Formato fecha"));

        buttonGroupFormatoFecha.add(jRadioButtonFechaLarga);
        jRadioButtonFechaLarga.setSelected(true);
        jRadioButtonFechaLarga.setText("Fecha larga");
        jRadioButtonFechaLarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFechaLargaActionPerformed(evt);
            }
        });

        buttonGroupFormatoFecha.add(jRadioButtonFechaCorta);
        jRadioButtonFechaCorta.setText("Fecha corta");
        jRadioButtonFechaCorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFechaCortaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFormatoFechaLayout = new javax.swing.GroupLayout(jPanelFormatoFecha);
        jPanelFormatoFecha.setLayout(jPanelFormatoFechaLayout);
        jPanelFormatoFechaLayout.setHorizontalGroup(
            jPanelFormatoFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormatoFechaLayout.createSequentialGroup()
                .addGroup(jPanelFormatoFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonFechaLarga)
                    .addComponent(jRadioButtonFechaCorta))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelFormatoFechaLayout.setVerticalGroup(
            jPanelFormatoFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormatoFechaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonFechaLarga)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonFechaCorta)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanelFormatoHora.setBorder(javax.swing.BorderFactory.createTitledBorder("Formato hora"));

        jRadioButtonHoras24.setSelected(true);
        jRadioButtonHoras24.setText("24 horas");
        jRadioButtonHoras24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHoras24ActionPerformed(evt);
            }
        });

        jRadioButtonHoras12.setText("12 horas (AM / PM)");
        jRadioButtonHoras12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHoras12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFormatoHoraLayout = new javax.swing.GroupLayout(jPanelFormatoHora);
        jPanelFormatoHora.setLayout(jPanelFormatoHoraLayout);
        jPanelFormatoHoraLayout.setHorizontalGroup(
            jPanelFormatoHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormatoHoraLayout.createSequentialGroup()
                .addGroup(jPanelFormatoHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonHoras24)
                    .addComponent(jRadioButtonHoras12))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanelFormatoHoraLayout.setVerticalGroup(
            jPanelFormatoHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormatoHoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonHoras24)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonHoras12)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Alarma"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(planificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(planificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonProgAlarma.setText("Programar alarma");
        jButtonProgAlarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProgAlarmaActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonProgAlarma, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(jPanelFormatoFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelFormatoHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFormatoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelFormatoHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonProgAlarma)
                    .addComponent(jButtonSalir))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonFechaLargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFechaLargaActionPerformed
        planificador.setFormatoFecha(true);
    }//GEN-LAST:event_jRadioButtonFechaLargaActionPerformed

    private void jRadioButtonFechaCortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFechaCortaActionPerformed
        planificador.setFormatoFecha(false);
    }//GEN-LAST:event_jRadioButtonFechaCortaActionPerformed

    private void jRadioButtonHoras24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHoras24ActionPerformed
        planificador.setFormatoHora(true);
    }//GEN-LAST:event_jRadioButtonHoras24ActionPerformed

    private void jRadioButtonHoras12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHoras12ActionPerformed
        planificador.setFormatoHora(false);
    }//GEN-LAST:event_jRadioButtonHoras12ActionPerformed

    private void jButtonProgAlarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProgAlarmaActionPerformed
        
        LocalDateTime fechaHora = ((Date)jSpinnerFechaHora.getValue()).toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
        String tarea = jTextFieldTarea.getText();
        
        planificador.setAlarma(new Alarma(fechaHora, tarea));
    }//GEN-LAST:event_jButtonProgAlarmaActionPerformed

    private void jTextFieldTareaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTareaKeyTyped
        if(jTextFieldTarea.getText().length() == 30){
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldTareaKeyTyped

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaPlanificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaPlanificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaPlanificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaPlanificador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaPlanificador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupFormatoFecha;
    private javax.swing.ButtonGroup buttonGroupFormatoHora;
    private javax.swing.JButton jButtonProgAlarma;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelFechaHora;
    private javax.swing.JLabel jLabelTarea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelFormatoFecha;
    private javax.swing.JPanel jPanelFormatoHora;
    private javax.swing.JRadioButton jRadioButtonFechaCorta;
    private javax.swing.JRadioButton jRadioButtonFechaLarga;
    private javax.swing.JRadioButton jRadioButtonHoras12;
    private javax.swing.JRadioButton jRadioButtonHoras24;
    private javax.swing.JSpinner jSpinnerFechaHora;
    private javax.swing.JTextField jTextFieldTarea;
    private planificador.Planificador planificador;
    // End of variables declaration//GEN-END:variables
}
