package clinica_veterinaria;

import java.awt.Component;
import java.awt.Container;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author andres
 */
public class DialogoNuevoCliente extends javax.swing.JDialog {

    /**
     * Creates new form DialogNuevoCliente
     */
    public DialogoNuevoCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Añadir nuevo cliente");
        this.setLocationRelativeTo(null);

        // Crear el modelo del Spinner (SpinnerDateModel)
        SpinnerDateModel dateModel = new SpinnerDateModel();
        dateModel.setValue(new Date()); // Establece la fecha actual como valor inicial

        // Asignar el modelo al JSpinner (jSpinner1)
        jSpinner1.setModel(dateModel);

        // Configurar el editor del Spinner con el formato deseado
        JSpinner.DateEditor dateEditor = new JSpinner.DateEditor(jSpinner1, "dd/MM/yyyy");
        jSpinner1.setEditor(dateEditor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupSexo = new javax.swing.ButtonGroup();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelCliente = new javax.swing.JPanel();
        jLabelCliente1 = new javax.swing.JLabel();
        jLabelDni = new javax.swing.JLabel();
        jTextFieldNombreCliente = new javax.swing.JTextField();
        jLabelDni1 = new javax.swing.JLabel();
        jTextFieldPrimerApe = new javax.swing.JTextField();
        jLabelDni2 = new javax.swing.JLabel();
        jTextFieldSegundoApe = new javax.swing.JTextField();
        jLabelDni4 = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelDni5 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelDni3 = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jPanelMascota = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombreMascota = new javax.swing.JTextField();
        jLabelCliente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNumIdentificacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanelSexo = new javax.swing.JPanel();
        jRadioButtonMacho = new javax.swing.JRadioButton();
        jRadioButtonHembra = new javax.swing.JRadioButton();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelTitulo.setBackground(new java.awt.Color(255, 204, 102));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTitulo.setText("Añadir nuevo cliente");
        jPanelTitulo.add(jLabelTitulo);

        jPanelCliente.setBackground(new java.awt.Color(255, 204, 0));
        jPanelCliente.setLayout(new java.awt.GridBagLayout());

        jLabelCliente1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelCliente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCliente1.setText("Cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 8, 0, 0);
        jPanelCliente.add(jLabelCliente1, gridBagConstraints);

        jLabelDni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDni.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 54, 0, 0);
        jPanelCliente.add(jLabelDni, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 116;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 6, 0, 0);
        jPanelCliente.add(jTextFieldNombreCliente, gridBagConstraints);

        jLabelDni1.setText("Primer Apellido:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 18, 0, 0);
        jPanelCliente.add(jLabelDni1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 6, 0, 0);
        jPanelCliente.add(jTextFieldPrimerApe, gridBagConstraints);

        jLabelDni2.setText("Segundo Apellido:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 18, 0, 0);
        jPanelCliente.add(jLabelDni2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 6, 0, 36);
        jPanelCliente.add(jTextFieldSegundoApe, gridBagConstraints);

        jLabelDni4.setText("Teléfono:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 53, 0, 0);
        jPanelCliente.add(jLabelDni4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        jPanelCliente.add(jTextFieldTelefono, gridBagConstraints);

        jLabelDni5.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 35, 0, 0);
        jPanelCliente.add(jLabelDni5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 212;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        jPanelCliente.add(jTextFieldEmail, gridBagConstraints);

        jLabelDni3.setText("Dirección:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 88, 0, 0);
        jPanelCliente.add(jLabelDni3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 371;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 9, 0);
        jPanelCliente.add(jTextFieldDireccion, gridBagConstraints);

        jPanelMascota.setBackground(new java.awt.Color(255, 204, 0));
        jPanelMascota.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 61, 0, 0);
        jPanelMascota.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 108;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 5, 0, 0);
        jPanelMascota.add(jTextFieldNombreMascota, gridBagConstraints);

        jLabelCliente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelCliente.setText("Mascota");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 0, 0);
        jPanelMascota.add(jLabelCliente, gridBagConstraints);

        jLabel2.setText("Nº Identificación:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 69, 0, 0);
        jPanelMascota.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 84;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanelMascota.add(jTextFieldNumIdentificacion, gridBagConstraints);

        jLabel4.setText("Tipo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 69, 0, 0);
        jPanelMascota.add(jLabel4, gridBagConstraints);

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perro", "Gato", "Ave", "Reptil", "Otro" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 0, 0);
        jPanelMascota.add(jComboBoxTipo, gridBagConstraints);

        jLabel5.setText("Fecha de nacimiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 6, 0, 0);
        jPanelMascota.add(jLabel5, gridBagConstraints);

        jPanelSexo.setBackground(new java.awt.Color(255, 204, 0));
        jPanelSexo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jRadioButtonMacho.setBackground(new java.awt.Color(255, 204, 0));
        buttonGroupSexo.add(jRadioButtonMacho);
        jRadioButtonMacho.setLabel("Macho");
        jRadioButtonMacho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMachoActionPerformed(evt);
            }
        });

        jRadioButtonHembra.setBackground(new java.awt.Color(255, 204, 0));
        buttonGroupSexo.add(jRadioButtonHembra);
        jRadioButtonHembra.setLabel("Hembra");

        javax.swing.GroupLayout jPanelSexoLayout = new javax.swing.GroupLayout(jPanelSexo);
        jPanelSexo.setLayout(jPanelSexoLayout);
        jPanelSexoLayout.setHorizontalGroup(
            jPanelSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSexoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonHembra)
                    .addComponent(jRadioButtonMacho))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanelSexoLayout.setVerticalGroup(
            jPanelSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSexoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonMacho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonHembra)
                .addGap(10, 10, 10))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 8;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 90, 6, 75);
        jPanelMascota.add(jPanelSexo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 63;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        jPanelMascota.add(jSpinner1, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButtonGuardar.setBackground(new java.awt.Color(51, 204, 0));
        jButtonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 162, 0, 0);
        jPanel1.add(jButtonGuardar, gridBagConstraints);

        jButtonCancelar.setBackground(new java.awt.Color(255, 51, 51));
        jButtonCancelar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 90, 0, 107);
        jPanel1.add(jButtonCancelar, gridBagConstraints);

        jButtonLimpiar.setBackground(new java.awt.Color(102, 204, 255));
        jButtonLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 100, 0, 0);
        jPanel1.add(jButtonLimpiar, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMachoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMachoActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        this.guardar();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.confirmarSalidadSinGuardar();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoNuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoNuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoNuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoNuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoNuevoCliente dialog = new DialogoNuevoCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void guardar() {
        StringBuilder errores = new StringBuilder(); // Para acumular los mensajes de error

        // Verificar que el campo "NombreCliente" no esté vacío y sea alfabético
        if (jTextFieldNombreCliente.getText().trim().isEmpty() 
                || !esAlfabetico(jTextFieldNombreCliente.getText())) {
            errores.append("El nombre del cliente debe ser un texto alfabético.\n");
        }

        // Verificar que el campo "PrimerApe" no esté vacío y sea alfabético
        if (jTextFieldPrimerApe.getText().trim().isEmpty() 
                || !esAlfabetico(jTextFieldPrimerApe.getText())) {
            errores.append("El primer apellido debe ser un texto alfabético.\n");
        }

        // Verificar que el campo "SegundoApe" sea alfabético (opcional, puede estar vacío)
        if (!jTextFieldSegundoApe.getText().trim().isEmpty() 
                && !esAlfabetico(jTextFieldSegundoApe.getText())) {
            errores.append("El segundo apellido debe ser un texto alfabético.\n");
        }

        // Verificar que el campo "NumIdentificacion" contenga solo dígitos
        if (jTextFieldNumIdentificacion.getText().trim().isEmpty() 
                || !esNumerico(jTextFieldNumIdentificacion.getText())) {
            errores.append("El número de identificación debe contener solo dígitos.\n");
        }

        // Verificar que el campo "Telefono" contenga solo dígitos
        if (jTextFieldTelefono.getText().trim().isEmpty() || !esNumerico(jTextFieldTelefono.getText())) {
            errores.append("El número de teléfono debe contener solo dígitos.\n");
        }

        // Verificar que el campo "Email" tenga formato válido
        if (jTextFieldEmail.getText().trim().isEmpty() || !esEmailValido(jTextFieldEmail.getText())) {
            errores.append("El email no tiene un formato válido.\n");
        }

        // Verificar que el campo "Direccion" no esté vacío
        if (jTextFieldDireccion.getText().trim().isEmpty()) {
            errores.append("La dirección no puede estar vacía.\n");
        }

        // Verificar que el sexo esté seleccionado
        if (buttonGroupSexo.getSelection() == null) {
            errores.append("Debe seleccionar el sexo (Macho o Hembra).\n");
        }

        // Verificar si hubo errores
        if (errores.length() > 0) {
            // Mostrar los errores acumulados
            JOptionPane.showMessageDialog(
                    this, 
                    errores.toString(), 
                    "Errores de validación", 
                    JOptionPane.ERROR_MESSAGE);
        } else {
            // Continuar con la lógica de guardado
            JOptionPane.showMessageDialog(
                    this, 
                    "Todos los datos son válidos. Guardando...", 
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private boolean esAlfabetico(String texto) {
        return texto.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$");
    }

    private boolean esNumerico(String texto) {
        return texto.matches("^\\d+$");
    }

    private boolean esEmailValido(String email) {
        return email.matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$");
    }

    private boolean esFechaValida(String fecha) {
        // Define el formato esperado de la fecha
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        formatoFecha.setLenient(false); // Asegura que la fecha sea estrictamente válida

        try {
            // Intenta analizar la fecha
            formatoFecha.parse(fecha);
            return true; // La fecha es válida
        } catch (ParseException e) {
            return false; // La fecha no es válida
        }
    }

    private void limpiar() {
        limpiarRecursivo(this.getContentPane()); // Llama al método recursivo en el contenedor principal
        this.buttonGroupSexo.clearSelection();  // Limpia la selección del grupo de botones
        this.jComboBoxTipo.setSelectedIndex(0); // Selecciona la primera opcion del combobox por defecto
    }

    private void limpiarRecursivo(Container container) {
        for (Component component : container.getComponents()) {
            if (component instanceof JTextField) {
                JTextField textField = (JTextField) component;
                textField.setText(""); // Limpiar el campo de texto
            } else if (component instanceof Container) {
                // Si el componente es un contenedor (como un JPanel), llama al método recursivo
                limpiarRecursivo((Container) component);
            }
        }
    }

    private void confirmarSalidadSinGuardar() {
        if (todosCamposTextoVacios(this) && this.buttonGroupSexo.getSelection() == null) {
            this.dispose();
            System.out.println(todosCamposTextoVacios(this));
        } else {
            String[] opciones = {"Sí", "No"};
            int resultado = JOptionPane.showOptionDialog(
                    null,
                    "Hay información sin guardar, ¿Estás segur@ que deseas cerrar?",
                    "Información de la aplicación",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.INFORMATION_MESSAGE,
                    null,
                    opciones,
                    opciones[0] // Botón por defecto
            );
            switch (resultado) {
                case 0: // Índice del botón "Sí"
                    this.dispose();
                    break;
                case 1: // Índice del botón "No"
                    System.out.println("Operación cancelada");
                    break;
                default: // Caso en que se cierra el diálogo
                    break;
            }
        }
    }

    private boolean todosCamposTextoVacios(Container container) {
        for (Component component : container.getComponents()) {
            if (component instanceof JTextField) {
                JTextField textField = (JTextField) component;
                if (!textField.getText().trim().isEmpty()) {
                    return false; // Si un campo no está vacío, devuelve false
                }
            } else if (component instanceof Container) {
                // Llamada recursiva para contenedores anidados
                if (!todosCamposTextoVacios((Container) component)) {
                    return false;
                }
            }
        }
        return true; // Si todos los campos están vacíos, devuelve true
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelCliente1;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelDni1;
    private javax.swing.JLabel jLabelDni2;
    private javax.swing.JLabel jLabelDni3;
    private javax.swing.JLabel jLabelDni4;
    private javax.swing.JLabel jLabelDni5;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JPanel jPanelMascota;
    private javax.swing.JPanel jPanelSexo;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JRadioButton jRadioButtonHembra;
    private javax.swing.JRadioButton jRadioButtonMacho;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNombreCliente;
    private javax.swing.JTextField jTextFieldNombreMascota;
    private javax.swing.JTextField jTextFieldNumIdentificacion;
    private javax.swing.JTextField jTextFieldPrimerApe;
    private javax.swing.JTextField jTextFieldSegundoApe;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
