package clinica_veterinaria;

import java.awt.Color;
import java.awt.Insets;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author andres
 */
public class FormularioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormularioPrincipal
     */
    public FormularioPrincipal() {
        initComponents();
        this.setTitle("Clínica veterinaria 'El Ángel'");
        this.setLocationRelativeTo(null);

        this.jButtonAnadir.setBackground(new Color(34, 139, 34));
        this.jButtonAnadir.setForeground(Color.WHITE);
        this.jButtonAnadir.setContentAreaFilled(true);

        this.jButtonSalir.setBackground(new Color(220, 20, 60));
        this.jButtonSalir.setForeground(Color.WHITE);
        this.jButtonSalir.setContentAreaFilled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelFondo = new javax.swing.JPanel();
        jLabelImagenFondo = new javax.swing.JLabel();
        jPanelBotones = new javax.swing.JPanel();
        jButtonAnadir = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();
        jMenuItemAnadir = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondo.setLayout(new java.awt.BorderLayout());

        jLabelImagenFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/veterinaria_640.jpg"))); // NOI18N
        jLabelImagenFondo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanelFondo.add(jLabelImagenFondo, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelFondo, java.awt.BorderLayout.CENTER);

        jPanelBotones.setBackground(new java.awt.Color(102, 153, 255));
        jPanelBotones.setLayout(new java.awt.GridBagLayout());

        jButtonAnadir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonAnadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono_guardar.png"))); // NOI18N
        jButtonAnadir.setText("Añadir Cliente");
        jButtonAnadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAnadir.setFocusPainted(false);
        jButtonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 156, 20, 0);
        jPanelBotones.add(jButtonAnadir, gridBagConstraints);

        jButtonSalir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono-cerrar.png"))); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalir.setFocusPainted(false);
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 130, 20, 177);
        jPanelBotones.add(jButtonSalir, gridBagConstraints);

        getContentPane().add(jPanelBotones, java.awt.BorderLayout.SOUTH);

        jPanelTitulo.setBackground(new java.awt.Color(102, 153, 255));
        jPanelTitulo.setLayout(new java.awt.BorderLayout());

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Bienvenid@s a la Clínica El Ángel");
        jPanelTitulo.add(jLabelTitulo, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelTitulo, java.awt.BorderLayout.PAGE_START);

        jMenuInicio.setText("Menu");
        jMenuInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItemAnadir.setText("Añadir Cliente");
        jMenuItemAnadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAnadirActionPerformed(evt);
            }
        });
        jMenuInicio.add(jMenuItemAnadir);

        jMenuBar1.add(jMenuInicio);

        jMenuAyuda.setText("Ayuda");
        jMenuAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAyudaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuAyuda);

        jMenuSalir.setText("Salir");
        jMenuSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirActionPerformed
        // TODO add your handling code here:
        DialogoNuevoCliente nuevoCliente = new DialogoNuevoCliente(this, rootPaneCheckingEnabled);
        nuevoCliente.setVisible(true);
    }//GEN-LAST:event_jButtonAnadirActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        this.confirmarSalida();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jMenuAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAyudaMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,
                "Esta aplicación permite añadir nuevos clientes y gestionar la clínica veterinaria",
                "Información de la aplicación",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuAyudaMouseClicked

    private void jMenuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalirMouseClicked
        // TODO add your handling code here:
        this.confirmarSalida();
    }//GEN-LAST:event_jMenuSalirMouseClicked

    private void jMenuItemAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAnadirActionPerformed
        // TODO add your handling code here:
        DialogoNuevoCliente nuevoCliente = new DialogoNuevoCliente(this, rootPaneCheckingEnabled);
        nuevoCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItemAnadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
    }

    private void confirmarSalida() {
        String[] opciones = {"Sí", "No"};
        int resultado = JOptionPane.showOptionDialog(
                null,
                "¿Estás segur@ que deseas salir de la aplicación?",
                "Información de la aplicación",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                opciones,
                opciones[0] // Botón por defecto
        );

        switch (resultado) {
            case 0: // Índice del botón "Sí"
                this.dispose();
                break;
            case 1: // Índice del botón "No"
                System.out.println("Operación cancelada");
                break;
            default: // Caso en que se cierra el diálogo
                break;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnadir;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelImagenFondo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JMenuItem jMenuItemAnadir;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelTitulo;
    // End of variables declaration//GEN-END:variables
}
