package Modelo;
// Generated 28-ene-2025 15:56:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Universidad generated by hbm2java
 */
public class Universidad  implements java.io.Serializable {


     private int codigo;
     private String nombre;
     private String provinciaUni;
     private Boolean privada;
     private Set estudiantes = new HashSet(0);

    public Universidad() {
    }

	
    public Universidad(int codigo) {
        this.codigo = codigo;
    }
    public Universidad(int codigo, String nombre, String provinciaUni, Boolean privada, Set estudiantes) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.provinciaUni = provinciaUni;
       this.privada = privada;
       this.estudiantes = estudiantes;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getProvinciaUni() {
        return this.provinciaUni;
    }
    
    public void setProvinciaUni(String provinciaUni) {
        this.provinciaUni = provinciaUni;
    }
    public Boolean getPrivada() {
        return this.privada;
    }
    
    public void setPrivada(Boolean privada) {
        this.privada = privada;
    }
    public Set getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set estudiantes) {
        this.estudiantes = estudiantes;
    }




}


